// <auto-generated />
using System;
using GymWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GymWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210509182821_initdb3")]
    partial class initdb3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GymWebApp.Models.Gymnast", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AgeSection")
                        .HasColumnType("int");

                    b.Property<int>("Apparatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PictureURL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("Gymnasts");
                });

            modelBuilder.Entity("GymWebApp.Models.Judges", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgeSections")
                        .HasColumnType("int");

                    b.Property<int>("Apparatuss")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GymnastID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PictureURL")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("GymnastID");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("GymWebApp.Models.Judges", b =>
                {
                    b.HasOne("GymWebApp.Models.Gymnast", "Gymnast")
                        .WithMany("Judges")
                        .HasForeignKey("GymnastID");

                    b.Navigation("Gymnast");
                });

            modelBuilder.Entity("GymWebApp.Models.Gymnast", b =>
                {
                    b.Navigation("Judges");
                });
#pragma warning restore 612, 618
        }
    }
}
